<? if ($this->apps && 0 < count($this->apps)): ?>
<table>
    <tr>
<? foreach ($this->listingFields as $field): ?>
        <th><?= $field ?></th>
<? endforeach ?>
    </tr>
<? foreach ($this->apps as $app): ?>
    <tr>
    <? foreach ($app->getListingData() as $value): ?>
        <td><?= $value ?></td>
    <? endforeach ?>
        <td>
            [ <a href="/delete/<?= $app->id ?>">delete</a> ]
        </td>
    </tr>
<? endforeach ?>
</table>
<? else: ?>
<p>No deployments found</p>
<? endif ?>
